name: setup
description: setup toolchain and cache

inputs:
  targets:
    required: false
    description: "Comma-separated string of additional targets to install"

runs:
  using: composite
  steps:
    - name: (setup) rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        cache: true
        target: ${{ inputs.targets }}
        rustflags: "" # override default rustflags

    - name: (setup) sccache
      uses: mozilla-actions/sccache-action@v0.0.7
    
    - name: (setup) environment variables for sccache
      shell: bash
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
        echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"
