name: Lint and Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
jobs:
  lint:
    name: lint
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache toolchain
        uses: Swatinem/rust-cache@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
            components: rustfmt, clippy
      - name: Check build
        run: |
          make check
      - name: Lint
        run: |
          make lint
  test:
    name: test
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache toolchain
        uses: Swatinem/rust-cache@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - name: Test
        run: |
          make test
  test-e2e:
    name: test-e2e
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        toolchain: [stable, beta, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache toolchain
        uses: Swatinem/rust-cache@v1
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: ${{ matrix.toolchain }}
            override: true
      - name: Install shellspec
        run: |
          # add shellspec bin to PATH
          echo $HOME/.local/bin >> $GITHUB_PATH
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
      - name: Test
        run: |
          make install
          make shellspec
