name: Lint and Test
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Lint
        run: |
          make lint

  test:
    name: test
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Test
        run: |
          make test

  test-e2e:
    name: test-e2e
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Install shellspec
        run: |
          # add shellspec bin to PATH
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          curl -fsSL https://git.io/shellspec | sh -s -- --yes
      - name: Test
        run: |
          make install
          make shellspec
